version: '3.8'

services:
  db:
    image: mongo:7.0
    container_name: eduflow_mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=eduflow_db

  web:
    build: .
    container_name: eduflow_web
    command: gunicorn --bind 0.0.0.0:8000 academy_suite.wsgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mongo_data: